<?php
/**
 * Created by PhpStorm.
 * User: bw_dev
 * Date: 13.05.2018
 * Time: 15:00
 */

namespace yozh\widget\widgets\grid;

use yozh\widget\widgets\grid\DataColumn;

class GridView extends \yii\grid\GridView
{
	/**
	 * @var string the default data column class if the class name is not explicitly specified when configuring a data column.
	 * Defaults to 'yii\grid\DataColumn'.
	 */
	public $dataColumnClass = DataColumn::class;
	
	public function renderTableRow( $model, $key, $index )
	{
		return parent::renderTableRow( $model, $key, $index ); // TODO: Change the autogenerated stub
	}
	
	
}