<?php
/**
 * Created by PhpStorm.
 * User: bw_dev
 * Date: 16.05.2018
 * Time: 8:59
 */

namespace yozh\widget\traits;

use yii\helpers\Html;
use yozh\base\components\helpers\Inflector;
use yozh\base\traits\ObjectTrait;
use yozh\widget\AssetBundle;

trait WidgetTrait
{
	use ObjectTrait;
	
	public $options;
	
	public $widgetId;
	
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		
		$AssetBundle = AssetBundle::register( $this->getView() );
		
		$namespaceId    = str_replace( '\\', '-', trim( $AssetBundle->namespace(), '\\' ) );
		$widgetId = $this->widgetId = $this->widgetId ?? strtolower( $namespaceId . '-' . Inflector::camel2id( $this->className( true ) ) );
		
		if( is_file( "{$AssetBundle->sourcePath}/js/$widgetId.js" ) ) {
			$AssetBundle->js[] = "js/$widgetId.js";
		}
		
		if( is_file( "{$AssetBundle->sourcePath}/css/$widgetId.css" ) ) {
			$AssetBundle->css[] = "css/$widgetId.css";
		}
		
		$this->options = $this->options ?? [];
		
		if( is_string( $this->options['class'] ?? false ) ) {
			$this->options['class'] = explode( ' ', $this->options['class'] );
		}
		
		$options = &$this->options;
		
		if( isset( $options['class'] ) && $options['class'] instanceof Closure ) {
			Html::addCssClass( $options, call_user_func_array( $options['class'], [ $this ] ) );
		}
		
		Html::addCssClass( $options, [
			'namespace' => $namespaceId,
			'widget'    => $widgetId,
		] );
		
	}
	
}