<?php
/**
 * Created by PhpStorm.
 * User: bw_dev
 * Date: 16.05.2018
 * Time: 8:59
 */

namespace yozh\widget\traits;

use yii\helpers\Html;
use yozh\base\traits\ObjectTrait;

trait WidgetTrait
{
	use ObjectTrait;
	
	/**
	 * @var array $options.
	 */
	public $options = [];
	
	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		
		$options = &$this->options;
		
		if( isset( $options['class'] ) && $options['class'] instanceof Closure ) {
			Html::addCssClass( $options, call_user_func_array( $options['class'], [ $this ] ) );
		}
		
		Html::addCssClass( $options, [ 'base_widget' => 'yozh-widget' ] );
		
	}
	
}